sudo: required
dist: trusty
language: node_js
python:
- '2.7'
jobs:
  include:
  - stage: EventHub Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=EventHubs/tests TEST_FILE=test_eventhub_logs.py
  - stage: EventHub Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=EventHubs/tests TEST_FILE=test_eventhub_metrics.py
  - stage: BlockBlobReader Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=BlockBlobReader/tests TEST_FILE=test_blobreader.py LOG_TYPE=logs
  - stage: BlockBlobReader Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=BlockBlobReader/tests TEST_FILE=test_blobreader.py LOG_TYPE=csv
  - stage: BlockBlobReader Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=BlockBlobReader/tests TEST_FILE=test_blobreader.py LOG_TYPE=json
before_install:
- curl https://bootstrap.pypa.io/get-pip.py | sudo python
- cd $FUNCTION_DIR
- pip install --user -r ../requirements.txt
script:
- python $TEST_FILE
env:
  global:
  - secure: q6CBd89cZCuSOLmv32K0zRB/VWsIOfqKA7hOf3z48KOrNz3WbAlcJZnDw+GQTF8IZwzTbMq3bFSGlmZg2rKhg3+kfTkisNHghIeVjbX62LYq0LrgsZuVWgyis1/QtBMzOhh5NMf3gVgP9TCu2yWfhNbBsdMOIfPeUtBGhXaUFvV+FLdo9VTFpy9RVQr+8zq0k1YPh4pV9NUz6dYqH3MLtqDWwqsHazNnGJDwnrpE90BTb9QeTxzZGSjyol3w6V//EsyhLTdxbHqwOBeB9580QI8088+tKCp1i9ZeQcLw8G/65St91hsF7eU+gaUA3dYVbEbqP2Dc5TgP65kFDkpU6dDeGo8mVRVzhY1vMtkQFF3iZpyssG/3M0neYIIUyWVDRLTO2ixIDK7DuD/00aOdcmf5RDd8a2l1rxPiwJ5whi0qNAgODa89mFo3ivUuYkbCRb6tGoU33wO1oqs1yQ2g0TFhcOXj8QSANXnocJqk9lcgyB9LXa0/i/JPYds1zcu1Sfxucx4ty4CPGmKMvwiY/yi92ePielQfUdEYERf8iPQ+Kc5Q6t2+F2Vgkxeqq5WYGs8nVoaxsebgBiUzgj75Lr9CO7yafoG1ZAAtwFxWlb8jQfJJo11KnKHnJovaLDE/CYhDp6dgc8OrSoLPJcFs/1X5DSML9tSMBl1T30q9Sd4=
  - secure: YX7ZP0aDz1tvQoXe31MmEFNjHEXWKQ+VybjxyGuNdDqQzHMYhVww3vv0socR9SaSNzVcvEzcyclj1x5r3DMpV1BmE82agJ/htkOwJN4t2qtKKJeBnR7KPiowroGKDnFDuF+FgYwIKtjsZZoyZR/1K+58dC52hVgxRVIpWShvO77R346jV3eQAs9tPx5lHzcPbyiYFnVluIns3XgQrBN0IaJLIJpn721Oe4IVy9/RlROc5JzoHW7VD/1O8gQPF8wYfYk1MQnyAQ+7p+hdi6iPgDiq5MNSXlRPldP1fm6LiJqGa7Ad0PGcuxMccdxsvAtsvuf4sfDkQtFh+iikP3rf/nEvTLUnbuGvf//ggMiawNM15jzopnmKyb4oDMpd71lCCl/+Y9Bs4J+bYKUEUz5q6+XEiPOvEBJgEmuLbvzbEQjuvJBEHL9sSCVNSODtXGh2TP055QPRBsW45FtmtzeQHG3uGjtmFbKIAXVpSgzX4HhhOwYVnl3Q0oTOOJC/eafmcQdrOIAwr/hSvE9jcf7PgQaeC1Jz9st+XTQ4nYe6GrimYPRD2+3Tq+P2zOsZAkHZoJjF4cHVEXJ4YPf1EWTj36Fj+SuWpBMzBx8QN2De18Bf5dM8xLrFCXfMzTauuJziF8GGh+VQ1xup9HDMimZuAn6kwiA54mKaEOerYXUI//c=
  - secure: NKskjIuT9xME12oc8bGugkLAR3fHq8hn1cAMrXkhr+617zmdMkyAceciC6CtVNlj8Lny7ut2Xmh30krcvcJJ/X0M0yfjDvOyIKcFTIfqTin/nVTkZQUex0OPllzBeSLXui6M4ThBW2q1ffIqH93ZcW2EtlkNYn5jkNRSYlBqjCGblrbuflwaDBAN/LvBQBYWOIQkSC2u9dhaImRNm9LoAZ68bNT0mTJKe2CK1EqrLR6pPk16/nviUBg6od1/nYJA5R2RqXvB2E4eqaGvKocVqQjMbgh/ULbUKWkvNK9vFPKly1ppxlyxkcGDvwPEhLDYE5a6FNsiF2o3cERkQIF6epksVPNZiBecz8iHPD2qyxl3l7Aai1bab8KAhDUX4dLrNSNkDWzaNOy/q/WSJATos+b2zPZ2rarPwMVMu90zHaxbQjnYOmpYKBP2+D+IxkUnypTS54/r6HmxMh/CWA8jOjXw3xdw1iJMbbk1ptZqqlu2VhDoArrDnIEr35Tcawam3XBpewe+tBd/S5tI4T1MW9W6sDFQZ4k5OYJyqYUqPOjV0UNQpkjjU2wnlBSUtUQBIgO+n2M9rDxe2M6vVZMiziaVGhYfwEjq3KgIujkFgWPpChUT5Nf9f8tjosy5QH/2/W9/CfCjJwXNccRVn3jiPUdYpD+asLip38GUE+7AogQ=
