sudo: required
dist: trusty
language: node_js
python:
- '2.7'
jobs:
  include:
  - stage: EventHub Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=EventHubs/tests TEST_FILE=test_eventhub_logs.py
  - stage: EventHub Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=EventHubs/tests TEST_FILE=test_eventhub_metrics.py
  - stage: BlockBlobReader Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=BlockBlobReader/tests TEST_FILE=test_blobreader.py LOG_TYPE=logs
  - stage: BlockBlobReader Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=BlockBlobReader/tests TEST_FILE=test_blobreader.py LOG_TYPE=csv
  - stage: BlockBlobReader Node 6
    node_js: '6.10'
    env: FUNCTION_DIR=BlockBlobReader/tests TEST_FILE=test_blobreader.py LOG_TYPE=json
before_install:
- sudo apt-get install python-pip
- cd $FUNCTION_DIR
- sudo pip install -r requirements.txt
script:
- python $TEST_FILE
env:
  global:
    secure: mv+B5a3KSV6tEXpQkpNIGWwC7ZKnLU3TqOZM8DwbkNtjkXRDmuEybRh8e31oz6GHfyFwl2U31FpW9pUNOHOBXQIGUWekE0VXzLfL88bCRI1dFDKQyF6UvcEx+hRpllOAwSSKyuBQpMcCWuS7f4m1Vb0HZ+1MIcDYhOU99pAIKhc76RHmrm8NeoNWZm0iuiuMmeyEtMj2iSrpgznBqz5/aot8uIKJDNmAktEKperGZBZ43fsYEp1FEKAU5iJhMQxgD2zGOpW287xsP/wnhdaE7tdZSN42p/UZrsu94MV7y81r4A2Vc/7IeGZBoUa1Xrt2QbB3xNPNmfUe/NMDLvKXIYDg55fY4JnTP04tfbTAlyPASZR7yJtZMwlqbyrSrs2NQMdE488moaa9DyJJgxgRZkRU+ev+UHwj9rqlsDw8kaXslN24Le90qZhSC55uTW0YTtDj3Y6MhplZw58VfUvQnNo4nou2aNFAITKs5qDko1u9+y4d52wLn0RbBvcnl55pRrzGvba/bKbxzPFre4zD9fY+qI8JT75quIdu3zwATd8ORFJ7wkAEa9e4FXNwr/7qFneDtJIWzfu6xc8l7ZY0Fd5lKmBXRwZIe1hNWI2V/SAElxgZ9oTuB25DZecxQ17kWJzkrwjtmoo7YNzveNtBjAHy4pYXevEt+AX3X4NgZVw=
